# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e52b4d43e24565112877e7ee8e2dec809c0d78665689906a6dac7ceeec8636b781a8b895ad5fa7ff5fcd50fe9d30cbae10ed037dcf86600d1894601c5a67192b

test:
  secret_key_base: 94fbc5a9adcb79c662fb47edf42908a7e6ccbedb1e4503593ed11408af3b8ce82e597946bcf37ae3c0ef23f26fb2781036daa51756273dac77fe8d0b429ad0d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
